
INSERT INTO TEACHER(ID, NAME, SURNAME, DOB, ADDRESS, PHONE, WORK_EXPERIENCE)
VALUES(TEACHER_SEQ.NEXTVAL, 'Ibrahim', 'Ibrahimov', TO_DATE('11-02-1992', 'DD-MM-YYYY'), 'Xirdalan', '2502545265', 8);

COMMIT;
--STUDENT 5 TEACHER - 1

INSERT INTO LESSON(ID, NAME, TIME, PRICE)
VALUES(LESSON_SEQ.NEXTVAL, 'Oracle SQL', 90, 140);

SELECT * FROM LESSON 
WHERE ACTIVE = 1;