
SELECT * FROM STUDENT 
WHERE ACTIVE = 1 ORDER BY NAME;

SELECT DISTINCT ADDRESS FROM STUDENT;

SELECT * FROM STUDENT 
WHERE ROWNUM <= 3;

UPDATE STUDENT SET ACTIVE = 1
WHERE ID = 2;

SELECT ROWNUM ID, NAME, SURNAME FROM STUDENT 
WHERE ACTIVE = 1;

--IN
SELECT * FROM STUDENT 
WHERE NAME IN ('Huseyn', 'Zaur') ;

--BETWEEN
SELECT * FROM STUDENT 
WHERE NAME BETWEEN 'F' AND 'M';

SELECT * FROM STUDENT
WHERE PHONE IS NOT NULL;

--LIKE
SELECT * FROM STUDENT
WHERE NAME LIKE 'Hus%';

SELECT * FROM STUDENT
WHERE NAME LIKE '%n';

SELECT * FROM STUDENT
WHERE NAME LIKE '%n%';

--burda ise 5 altdanxett(vildcard) istifade edilib, yeni 5 herfli olan adlari getirecek.
SELECT * FROM STUDENT
WHERE NAME LIKE '_____';

--hem u hem de u(Aze) axtarmaq ucun istifade olunan versiyasi
SELECT * FROM STUDENT
WHERE NAME LIKE 'H_seyn';

--ALYANS
SELECT NAME||' '||SURNAME FROM STUDENT
WHERE ACTIVE = 1;

SELECT NAME||' '||SURNAME AS FULLNAME FROM STUDENT
WHERE ACTIVE = 1;

SELECT NAME||' '||SURNAME FULLNAME FROM STUDENT
WHERE ACTIVE = 1;

SELECT NAME||' '||SURNAME FULLNAME FROM STUDENT S
WHERE S.ACTIVE = 1 ;


SELECT * FROM STUDENT 
WHERE ACTIVE = 1;