CREATE TABLE TEACHER
(
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    SURNAME VARCHAR2(50) NOT NULL,
    DOB DATE,
    ADDRESS VARCHAR2(100),
    PHONE VARCHAR2(30),
    WORK_EXPERIENCE INTEGER,
    DATA_DATE DATE DEFAULT SYSDATE,
    ACTIVE INTEGER DEFAULT 1 
);

CREATE TABLE LESSON
(
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    TIME INTEGER,
    PRICE FLOAT,
    DATA_DATE DATE DEFAULT SYSDATE,
    ACTIVE INTEGER DEFAULT 1
);

CREATE TABLE STUDENT_ADD_INFO
(
    ID NUMBER PRIMARY KEY,
    UNIVERSITY VARCHAR2(100),
    FACULTY VARCHAR2(100),
    EMAIL VARCHAR2(50),
    HOME_ADDRESS VARCHAR2(100),
    STUDENT_ID NUMBER,
    DATA_DATE DATE DEFAULT SYSDATE,
    ACTIVE INTEGER DEFAULT 1
);

CREATE TABLE TEACHER_LESSON
(
    ID NUMBER PRIMARY KEY,
    TEACHER_ID NUMBER,
    LESSON_ID NUMBER,
    DATA_DATE DATE DEFAULT SYSDATE,
    ACTIVE INTEGER DEFAULT 1
);

CREATE TABLE PAYMENT
(
    ID NUMBER PRIMARY KEY, 
    STUDENT_ID NUMBER,
    TEACHER_ID NUMBER,
    LESSON_ID NUMBER,
    AMOUNT FLOAT,
    PAY_DATE DATE DEFAULT SYSDATE,
    ACTIVE INTEGER DEFAULT 1
);

--Cedvele baxmaq ucun command
DESC TEACHER;