SELECT * FROM STUDENT;

SELECT ID, NAME, SURNAME FROM STUDENT ;

SELECT * FROM STUDENT WHERE ID = 1;

--COMMENT

SELECT * FROM STUDENT WHERE NAME = 'Huseyn';

SELECT * FROM STUDENT WHERE SURNAME = 'Ahadov' AND NAME = 'Zaur';

SELECT * FROM STUDENT WHERE NAME = 'Huseyn' OR SURNAME = 'Novruzov';

SELECT * FROM STUDENT WHERE LOWER(SURNAME) = LOWER('AHADOV');

SELECT UPPER(NAME) FROM STUDENT;

--INSERT

INSERT INTO STUDENT(ID, NAME, SURNAME, ADDRESS) VALUES(4,'Feqan', 'Yehyazade', 'Xirdalan');

ROLLBACK;

COMMIT;

INSERT INTO STUDENT 
VALUES(5,'Xeyal', 'Ferecov', 'Sumqayit', TO_DATE('2001-01-27', 'YYYY-MM-DD'), '070-5054648', SYSDATE, 1);

--Update

UPDATE STUDENT SET ADDRESS = 'Sumgait'
WHERE ID = 5;

UPDATE STUDENT SET DOB = TO_DATE('08-10-2001', 'DD-MM-YYYY')
WHERE ID = 4;

ALTER TABLE STUDENT ADD UPDATE_DATE DATE;

--DELETE
DELETE FROM STUDENT WHERE ID = 5;

SELECT * FROM STUDENT WHERE ACTIVE = 1;