
ALTER TABLE PAYMENT
ADD CONSTRAINT FK_STUDENT_ID 
FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID);

ALTER TABLE PAYMENT
ADD CONSTRAINT FK_TEACHER_ID
FOREIGN KEY (TEACHER_ID) REFERENCES TEACHER(ID);

ALTER TABLE PAYMENT
ADD CONSTRAINT FK_LESSON_ID
FOREIGN KEY (LESSON_ID) REFERENCES LESSON(ID);

ALTER TABLE STUDENT
ADD TEST_ID1 NUMBER;

--eyni anda coxlu column elave etmek ucun 

ALTER TABLE STUDENT
ADD (TEST_ID2 VARCHAR2(50),
     TEST_ID3 NUMBER);
     
ALTER TABLE STUDENT
MODIFY TEST_ID2 NUMBER;

ALTER TABLE STUDENT
RENAME COLUMN TEST_ID2 TO TEST2;

ALTER TABLE STUDENT 
DROP COLUMN TEST2;     

--CEDVELI SILMEK UCUN DROP DAN ISTIFADE OLUNUR;

DROP TABLE STUDENT;