SELECT * FROM STUDENT;

SELECT * FROM STUDENT_ADD_INFO;

SELECT S.ID, S.NAME, S.SURNAME, SAI.UNIVERSITY, SAI.FACULTY, SAI.EMAIL FROM STUDENT S, STUDENT_ADD_INFO SAI
WHERE SAI.STUDENT_ID = S.ID AND S.ACTIVE = 1;

--INNER JOIN
SELECT S.ID, S.NAME, S.SURNAME, SAI.UNIVERSITY, SAI.FACULTY, SAI.EMAIL FROM STUDENT S 
INNER JOIN STUDENT_ADD_INFO SAI ON S.ID = SAI.STUDENT_ID
WHERE S.ACTIVE = 1 AND SAI.ACTIVE = 1;

--LEFT JOIN
SELECT S.ID, S.NAME, S.SURNAME, SAI.UNIVERSITY, SAI.FACULTY, SAI.EMAIL FROM STUDENT S 
LEFT JOIN STUDENT_ADD_INFO SAI ON S.ID = SAI.STUDENT_ID
WHERE S.ACTIVE = 1 ;

--RIGHT JOIN
SELECT S.ID, S.NAME, S.SURNAME, SAI.UNIVERSITY, SAI.FACULTY, SAI.EMAIL FROM STUDENT S 
FULL JOIN STUDENT_ADD_INFO SAI ON S.ID = SAI.STUDENT_ID ;


ALTER TABLE TEACHER 
ADD LESSON_ID NUMBER;

SELECT T.ID, T.NAME, T.SURNAME, L.NAME LESSON_NAME FROM TEACHER T
INNER JOIN LESSON L ON T.LESSON_ID = L.ID
WHERE T.ACTIVE = 1 ORDER BY T.ID;