SELECT TL.ID, T.NAME||' '||T.SURNAME TEACHER_FULLNAME, L.NAME LESSON_NAME FROM TEACHER_LESSON TL 
INNER JOIN TEACHER T ON TL.TEACHER_ID = T.ID
INNER JOIN LESSON L ON TL.LESSON_ID = L.ID
WHERE TL.ACTIVE  = 1 ORDER BY TL.ID;

SELECT TL.ID, T.NAME||' '||T.SURNAME TEACHER_FULLNAME, L.NAME LESSON_NAME FROM TEACHER_LESSON TL 
RIGHT JOIN TEACHER T ON TL.TEACHER_ID = T.ID
FULL JOIN LESSON L ON TL.LESSON_ID = L.ID ;


--UNION AND UNION ALL

SELECT ID , NAME, SURNAME FROM STUDENT
UNION 
SELECT ID, NAME, SURNAME FROM TEACHER;

-- burda rownum isletmekle biz ozumuz ucun normal siraladiq, 2-ci select olan hisseye de alyas olaraq S adi qoyduq. 
-- S* da butun melumatlari getirir.

SELECT ROWNUM ID, S.* FROM (SELECT NAME, SURNAME FROM STUDENT
UNION 
SELECT NAME, SURNAME FROM TEACHER) S;